### ISSUE TITLE
[REFACTOR] Fix DOTWEEN warnings

### ISSUE THREAD

**Issue by AngieDutra** [lambdaclass/champions_of_mirra#1367]
## 🚧 Refactor

All scripts using dotween need a refactor to prevent this warning:

<img width="846" alt="Captura de pantalla 2024-01-29 a la(s) 10 58 07" src="https://github.com/lambdaclass/curse_of_mirra/assets/82987608/5b630dbf-185e-4031-9d8d-e42e8e3f4c8b">

This happens when the scene changes since dotween keeps running and the objects are no longer loaded

### Implementation

- Maybe using .Pause() .Complete() or .Kill() before the scene changes can prevent this from happening
- Add DOTWEEN to Title screen animations

**Comment by mgrunwaldt** [comment]
What is the status of this ticket? @saugon @AngieDutra @BertovDev
