### ISSUE TITLE
[DESIGN] Valtimer's and Uma's animations in endgame screen are not loop

### ISSUE THREAD

**Issue by AngieDutra** [lambdaclass/champions_of_mirra#1503]
## 🎨 Design
Valtimer stays like that and he could easyly go back to idle or have the animation looped. Uma's animations too.
<img width="330" alt="Captura de pantalla 2024-02-26 a las 12 13 28 p  m" src="https://github.com/lambdaclass/curse_of_mirra/assets/82987608/791941f3-dec5-4cfa-8e92-78fe75becff5">

In Uma's victory case is more complicated since she throws her knife. It should be contemplated a refactor of this animation for this screen to work

**Comment by mgrunwaldt** [comment]
This happens to all animations in the endgame screen right?
