### ISSUE TITLE
[BUG] Fix skills input radius, width and angle

### ISSUE THREAD

**Issue by saugon** [lambdaclass/champions_of_mirra#1535]
### Skills input radius
Most of the skills have the radius value hardcoded. We need to map them with the ones sent by the backend.

### Skills input width and angle
Verify that the skills angles (for the cone type) and the width (for Direction type) are correctly mapped and displayed. For example, H4ck's basic attack cone angle doesn't match the angle in which the projectiles are shot.

**Comment by BertovDev** [comment]
This ticket includes : https://github.com/lambdaclass/curse_of_mirra/issues/1563 ?

Also I believe we should discuss and define values for the config
https://github.com/lambdaclass/curse_of_mirra/issues/1563

**Comment by BertovDev** [comment]
We have to calculate each indicator correctly once https://github.com/lambdaclass/mirra_backend/issues/431 its done.
