### ISSUE TITLE
[DESIGN] New character list background

### ISSUE THREAD

**Issue by saugon** [lambdaclass/champions_of_mirra#1558]
## 🎨 Design
Design and draw a new background for the character list screen, considering the relation and contrast between it and the character boxes.

**Comment by jazimp** [comment]
References: 
![test 2](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/6069d0d1-f053-4253-95c9-2cf8413c731b)
![test 1](https://github.com/lambdaclass/curse_of_mirra/assets/134973476/b9a10b49-bf3a-4959-a9c7-a9b941c2ee16)
