### ISSUE TITLE
[BUG] Sand storm cut by wall

### ISSUE THREAD

**Issue by AngieDutra** [lambdaclass/champions_of_mirra#1593]
## 🐛 Bug Report

There is no clear solution stablished for this but the agreement here is it's not looking good and the illusion of sand storm breaks here

https://github.com/lambdaclass/curse_of_mirra/assets/82987608/43d9d91c-2e8a-48d5-8bcd-25ef83cfa8ba

**Comment by mgrunwaldt** [comment]
@AngieDutra why can't we do like with the fire particles vfx that don't have this problem?
