### ISSUE TITLE
[FEATURE] Displaying connectivity Icon for connection issues 

### ISSUE THREAD

**Issue by saugon** [lambdaclass/champions_of_mirra#1617]
## 🚀 Feature
In this task, we aim to show a connectivity icon on the screen to alert players when they encounter connectivity issues during gameplay. It involves researching the criteria for determining when a connection is unstable and identifying optimal moments to trigger the icon.

We can use this [icon](https://github.com/lambdaclass/curse_of_mirra/assets/6811225/81d5eb75-367f-4934-9b50-c9fc06e96bdf) in the meantime. Related to #1614

**Comment by jazimp** [comment]
https://drive.google.com/drive/folders/1JvzwC4_Blk11WDn96eKysPKZkIBBY9l_?usp=drive_link reference, asset and animation reference
