### ISSUE TITLE
[FEATURE] Quests screen implementation

### ISSUE THREAD

**Issue by saugon** [lambdaclass/champions_of_mirra#1682]
## 🚀 Feature
This issue focuses on implementing the Quests screen in Unity utilizing the provided design. The goal is to incorporate the designed layout and functionalities:

- Tab system for daily and weekly quests.
- Current daily and weekly quests list.
- Quest card:
  - Quest description and reward.
  - Quest status.
  - Quest progression.
  - Action: claim.
- Rerolling feature:
  - When the player taps on reroll, the quests that can be rerolled will be highlighted, allowing the player to tap one of them to proceed with the quest roll. Once performed, the screen should return to its normal state.

BONUS:
- Add Quests link in the main screen:
  - Change the button text, now it says "Daily Quest", it should say "Quests"
  - Remove the "soon" badge
  - Add the hexagon above the button, with the corresponding number indicating the quantity of quests available to claim

**Comment by jazimp** [comment]
Assets: https://drive.google.com/drive/folders/1ZpIXTO4d0sZbCJ8m62tDgiWJEX3Jlo8w?usp=drive_link
Buttons: https://drive.google.com/drive/folders/1h93h0kjVentkQGeoLqCXmc7HB0Y7pBGr?usp=drive_link
Background: https://drive.google.com/drive/folders/1Xw1OrKr1cw9cX-T7HgFbgeXygWx8hbPM?usp=drive_link
Hexagons: https://drive.google.com/drive/folders/1PpQOQ_HblQI8gKZnhLf8usDn_wvV0dir?usp=drive_link
Prototype: https://www.figma.com/file/qMZIYXmOCw8JXVEZ4m6nWu/Untitled?type=design&node-id=0%3A1&mode=design&t=TgMcJz5nkgEsjN7z-1
