### ISSUE TITLE
[FEATURE] New health bar and power up 

### ISSUE THREAD

**Issue by jazimp** [lambdaclass/champions_of_mirra#1861]
## 🚀 Feature

This new design integrates the information of the power-ups with the health bar.
In the assets folder, the elements corresponding to the enemy are separated from those corresponding to your information as a player to avoid confusion.

### Reference

![reference](https://github.com/lambdaclass/champions_of_mirra/assets/134973476/5b9edcb0-1a69-4524-ac3b-1f70e0184800)

Reference for power-ups: (in this case, the numbers only need to have a black shadow)
<img width="877" alt="reference1" src="https://github.com/lambdaclass/champions_of_mirra/assets/134973476/1b2b56a9-498c-479b-b057-78a14e715c39">

### Assets

https://drive.google.com/drive/folders/1r1KxmgHrhk1ZzX1sx1f0_VOG-RKXq9qn?usp=drive_link

### Additional context

Each player should start the match with the lightning icon in the power-up container to avoid displaying a 0. When the player starts obtaining power-ups, the icon should be replaced with the corresponding number.

As a bonus, this design adds:

1. An extra bar indicating the damage the character receives
2. A number accompanying that information

**Comment by mgrunwaldt** [comment]
We also need this for crates!
