### ISSUE TITLE
Targeting strategies

### ISSUE THREAD

**Issue by martinacantaro** [lambdaclass/champions_of_mirra#325]
Implement the different methods according to which the champions are going to choose their targets

1 PR per each strategy

- [x] Nearest/Furthest
- [ ] Lowest stat/highest stat ( 1 day)
- [ ] Frontline / Backline ( 1 day)
- [ ] Self (2 hs)
- [ ] All (2 hs)
- [x] Random

**Comment by lotuuu** [comment]
I've split this issue into 4 atomic issues
