### ISSUE TITLE
Executions

### ISSUE THREAD

**Issue by martinacantaro** [lambdaclass/champions_of_mirra#329]
Requirements: https://www.notion.so/lambdaclass/Executions-dd3daa21250848f99b4e6aa6bd2ec468

Complete each item in a separate PR

- [x] DealDamage
- [ ] DealDamageOverTime (using Executions over time) -- Note: this item needs discussion with Marco and will take longer than the others (2 - 3 days)
- [ ] AddEnergy (2 hs w/o tests)
- [ ] Heal (2 hs w/o tests)

**Comment by lotuuu** [comment]
I've split this PR into 3 atomic ones
