### ISSUE TITLE
Permanent Skills

### ISSUE THREAD

**Issue by martinacantaro** [lambdaclass/champions_of_mirra#330]
There are four types of skills:

- instantaneous
- permanent (for example Debuff) - it stays active during the whole battle unless a counter is applied. For example, debuffs are reversed with Dispel
- temporary
- periodic (energy drain/gain)

**Comment by lotuuu** [comment]
These are already implemented :D

https://github.com/lambdaclass/mirra_backend/blob/0b2c2441b893cbcd96d7b75e2929080d9939f06c/apps/champions/lib/champions/battle/simulator.ex#L189
