### ISSUE TITLE
Design the Dungeon mode in the Backend

### ISSUE THREAD

**Issue by martinacantaro** [lambdaclass/champions_of_mirra#409]
depends on #152

After the design is done, create tickets for the implementation

https://www.notion.so/lambdaclass/Dungeon-d6d9784fd4724312bff013f4c71076cb

**Comment by marco-paulucci** [comment]
config spec is done:
https://www.notion.so/lambdaclass/Dungeon-8a0e699c32e147f5857a813d41e69abc?pvs=9
