### ISSUE TITLE
[FEATURE] Implement basic bush behavior

### ISSUE THREAD

**Issue by mgrunwaldt** [lambdaclass/champions_of_mirra#846]
## 🚀 Feature

- Characters should receive a "hidden" state from backend. 
- Toggle enemies characters on/off based on visibility data provided by the backend.

Ref:
- https://github.com/lambdaclass/curse_of_myrra/pull/880 (`gh-846-basic-bush-behaviour`)

**Comment by SofiaVld** [comment]
https://drive.google.com/drive/folders/189HxxpwjZtmN87eHf43qUcMnMrUA210C?usp=drive_link
